# Ruff configuration file
# This file provides additional Ruff settings not covered in pyproject.toml

# Extend the base configuration from pyproject.toml
extend = "pyproject.toml"

# Additional settings for specific environments
[lint.extend-per-file-ignores]
"__init__.py" = ["F401"]  # Allow unused imports in __init__.py files
"**/test_*.py" = ["D"]    # Disable docstring requirements in test files
"**/conftest.py" = ["D"]  # Disable docstring requirements in conftest files 