name: Continuous Integration

description: This project is a continuous integration pipeline for an object detection system. It is a simple pipeline that uses GitHub Actions test the code.

on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      
      - name: Run tests with coverage
        run: uv run pytest --cov=src --cov-report=term --cov-report=html